apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PVC_NAME}
  labels:
    app: afd-recipe
spec:
  accessModes:
    - ${PVC_ACCESS_MODE}
  storageClassName: ${STORAGE_CLASS}
  resources:
    requests:
      storage: ${MODEL_PVC_SIZE}
